# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_bDve_TVgFhpP_9kRichTSLSVl-mdDW
"""

import requests
import time
import smtplib
from email.mime.text import MIMEText

def check_website(url, email, interval=60, timeout=5):
    """
    Checks if a website is reachable at a specified interval and sends an email notification if it's down.

    Args:
        url: The URL of the website to check.
        email: The email address to send notifications to.
        interval: The time interval (in seconds) between checks.
        timeout: The timeout (in seconds) for the request.
    """

    while True:
        try:
            response = requests.get(url, timeout=timeout)
            response.raise_for_status()
            print(f"{time.strftime('%Y-%m-%d %H:%M:%S')}: Website {url} is reachable (Status code: {response.status_code})")
        except requests.exceptions.RequestException as e:
            print(f"{time.strftime('%Y-%m-%d %H:%M:%S')}: Website {url} is down! Error: {e}")
            send_email_notification(email, url, str(e))

        time.sleep(interval)


def send_email_notification(email, url, error_message):
    """Sends an email notification."""

    sender_email = "https://mycampus.uok.ac.rw/"
    sender_password = "12345"
    recipient_email = "irakozejoel@gmail.com"

    msg = MIMEText(f"Website {url} is down!\nError: {error_message}")
    msg["Subject"] = "Website Down Alert"
    msg["From"] = sender_email
    msg["To"] = recepient_email

    try:
        with smtplib.SMTP_SSL("irakozejoel.@gmail.com", 465) as server:
            server.sendmail(sender_email, email, msg.as_string())
        print(f"Email notification sent to {email}")
    except Exception as e:
        print(f"Failed to send email notification: {e}")


if __name__ == "__main__":
    website_url = "https://mycampus.uok.ac.rw/"
    recipient_email = "irakozejoel9@gmail.com"
    check_website(website_url, recipient_email)